"""rename upper clmn

Revision ID: 2232c08854cc
Revises: 8a1e646f1c3d
Create Date: 2024-01-10 09:34:12.925979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2232c08854cc'
down_revision: Union[str, None] = '8a1e646f1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('upper_name', sa.Text(), nullable=True))
    op.drop_column('product', 'upperName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('upperName', sa.TEXT(), nullable=True))
    op.drop_column('product', 'upper_name')
    # ### end Alembic commands ###
