"""comment

Revision ID: 8a1e646f1c3d
Revises: b7d05e92f857
Create Date: 2024-01-09 17:13:56.739604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1e646f1c3d'
down_revision: Union[str, None] = 'b7d05e92f857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('upperName', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'upperName')
    # ### end Alembic commands ###
