"""add comment column in product

Revision ID: d80b1a69017b
Revises: c25cb2f1a320
Create Date: 2024-05-06 17:15:44.479048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80b1a69017b'
down_revision: Union[str, None] = 'c25cb2f1a320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'comment')
    # ### end Alembic commands ###
