"""2rename upper clmn

Revision ID: da0846a004cd
Revises: 2232c08854cc
Create Date: 2024-01-10 09:37:03.589306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0846a004cd'
down_revision: Union[str, None] = '2232c08854cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('search_name', sa.Text(), nullable=True))
    op.drop_column('product', 'upper_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('upper_name', sa.TEXT(), nullable=True))
    op.drop_column('product', 'search_name')
    # ### end Alembic commands ###
