# Generated by Django 3.2.16 on 2023-10-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0002_auto_20231010_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name_plural': 'Домены'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name_plural': 'Ссылки'},
        ),
        migrations.CreateModel(
            name='Domain_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя настройки')),
                ('tag', models.TextField(verbose_name='Имя тега')),
                ('attr', models.TextField(verbose_name='Имя атрибута')),
                ('attr_val', models.TextField(verbose_name='Значение атрибута')),
                ('content_type', models.CharField(choices=[('price', 'Цена -> int'), ('name', 'Название -> str'), ('chars', 'Характеристики -> list'), ('other_str', 'прочее -> str'), ('other_list', 'прочее -> list')], max_length=50, verbose_name='Тип содержимого')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_parser.domain', verbose_name='Домен')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
