# Generated by Django 3.2.16 on 2023-10-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_parser', '0003_auto_20231010_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain_setting',
            options={'verbose_name_plural': 'Настройки для парсинга'},
        ),
        migrations.RemoveField(
            model_name='domain_setting',
            name='name',
        ),
    ]
